const express = require('express');
const router = express.Router();
const PDFDocument = require('pdfkit');
const Vital = require('../models/Vital');

// Generate PDF report
router.get('/:userId/pdf', async (req, res) => {
  try {
    const days = parseInt(req.query.days) || 7;
    const since = new Date();
    since.setDate(since.getDate() - days);
    const vitals = await Vital.find({ userId: req.params.userId, date: { $gte: since } }).sort({ date: 1 });

    const doc = new PDFDocument({ margin: 50 });
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', 'attachment; filename=healthsync-report.pdf');
    doc.pipe(res);

    // Header
    doc.fontSize(24).fillColor('#6366f1').text('HealthSync', { align: 'center' });
    doc.fontSize(12).fillColor('#666').text('Smart Healthcare Report', { align: 'center' });
    doc.moveDown();
    doc.fontSize(10).fillColor('#999').text(`Generated: ${new Date().toLocaleDateString()} | Period: Last ${days} days`, { align: 'center' });
    doc.moveDown(2);

    // Summary
    doc.fontSize(16).fillColor('#1f2937').text('Health Summary');
    doc.moveDown(0.5);

    if (vitals.length === 0) {
      doc.fontSize(12).fillColor('#666').text('No vitals recorded in this period.');
    } else {
      const avgSugar = Math.round(vitals.filter(v => v.sugarFasting).reduce((s, v) => s + v.sugarFasting, 0) / (vitals.filter(v => v.sugarFasting).length || 1));
      const avgSystolic = Math.round(vitals.filter(v => v.bpSystolic).reduce((s, v) => s + v.bpSystolic, 0) / (vitals.filter(v => v.bpSystolic).length || 1));
      const avgDiastolic = Math.round(vitals.filter(v => v.bpDiastolic).reduce((s, v) => s + v.bpDiastolic, 0) / (vitals.filter(v => v.bpDiastolic).length || 1));

      doc.fontSize(12).fillColor('#374151');
      doc.text(`Records in period: ${vitals.length}`);
      doc.text(`Average Fasting Sugar: ${avgSugar} mg/dL`);
      doc.text(`Average Blood Pressure: ${avgSystolic}/${avgDiastolic} mmHg`);
      doc.moveDown();

      // Vitals Table
      doc.fontSize(16).fillColor('#1f2937').text('Vital Records');
      doc.moveDown(0.5);

      // Table header
      const tableTop = doc.y;
      doc.fontSize(10).fillColor('#6366f1');
      doc.text('Date', 50, tableTop, { width: 100 });
      doc.text('Sugar (F)', 150, tableTop, { width: 70 });
      doc.text('Sugar (PM)', 220, tableTop, { width: 70 });
      doc.text('BP', 290, tableTop, { width: 80 });
      doc.text('HR', 370, tableTop, { width: 50 });
      doc.moveDown();

      // Draw line
      doc.moveTo(50, doc.y).lineTo(450, doc.y).stroke('#e5e7eb');
      doc.moveDown(0.3);

      vitals.forEach(v => {
        if (doc.y > 700) {
          doc.addPage();
        }
        const y = doc.y;
        doc.fontSize(9).fillColor('#374151');
        doc.text(new Date(v.date).toLocaleDateString(), 50, y, { width: 100 });
        doc.text(v.sugarFasting ? `${v.sugarFasting}` : '-', 150, y, { width: 70 });
        doc.text(v.sugarPostMeal ? `${v.sugarPostMeal}` : '-', 220, y, { width: 70 });
        doc.text(v.bpSystolic ? `${v.bpSystolic}/${v.bpDiastolic}` : '-', 290, y, { width: 80 });
        doc.text(v.heartRate ? `${v.heartRate}` : '-', 370, y, { width: 50 });
        doc.moveDown(0.5);
      });

      // Insights
      doc.moveDown();
      doc.fontSize(16).fillColor('#1f2937').text('AI Insights');
      doc.moveDown(0.5);

      if (vitals.length >= 2) {
        const first = vitals[0];
        const last = vitals[vitals.length - 1];
        if (first.sugarFasting && last.sugarFasting) {
          const change = ((last.sugarFasting - first.sugarFasting) / first.sugarFasting * 100).toFixed(1);
          doc.fontSize(11).fillColor(change < 0 ? '#16a34a' : '#dc2626');
          doc.text(change < 0
            ? `✅ Fasting sugar improved by ${Math.abs(change)}%`
            : `⚠️ Fasting sugar increased by ${change}%`
          );
        }
        if (first.bpSystolic && last.bpSystolic) {
          const change = ((last.bpSystolic - first.bpSystolic) / first.bpSystolic * 100).toFixed(1);
          doc.fontSize(11).fillColor(change < 0 ? '#16a34a' : '#dc2626');
          doc.text(change < 0
            ? `✅ Blood pressure improved by ${Math.abs(change)}%`
            : `⚠️ Blood pressure increased by ${change}%`
          );
        }
      }
    }

    doc.moveDown(2);
    doc.fontSize(8).fillColor('#999').text('This report is generated by HealthSync AI and is for informational purposes only. Always consult your healthcare provider.', { align: 'center' });

    doc.end();
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

module.exports = router;
